// Define and export a metadata object for the page
export const metadata = {
  title: 'Next.js', // Page title
  description: 'Generated by Next.js', // Page description
};

// Default export the RootLayout component
export default function RootLayout({ children }) {
  // The component returns an HTML structure
  return (
    <html lang="en"> {/* Set the language attribute of the page to English */}
      <body>{children}</body> {/* Render the child components passed to the component */}
    </html>
  );
}
